#include "GuiControl.h"

const QString GuiControl::MESSAGE_AVAILABLE_COMMANDS =
        "<font size=3 face=\"MV Boli\" color = \"orange\">"
        "Available Commands: add, delete, mark, unmark, "
        "edit and find</font>";

GuiControl::GuiControl(QObject *parent) :
    QObject(parent)
{
    //Connecting local slot to signal for text input
    //generated by Standard UI
    connect(&standardGui,SIGNAL(relay(QString)),
            this,SLOT(check(QString)));

    //Connecting local slot to signal for text input
    //generated by Seample UI
    connect(&seampleGui,SIGNAL(relay(QString)),
            this,SLOT(check(QString)));

    //Connecting local slot to signal for text input
    //generated by Standard UI when enter key is pressed
    connect(&standardGui,SIGNAL(run(QString)),
            this,SLOT(passScheduler(QString)));

    //Connecting local slot to signal for text input
    //generated by Seample UI when enter key is pressed
    connect(&seampleGui,SIGNAL(run(QString)),
            this,SLOT(passScheduler(QString)));

    //Connecting local slot to signal generated when a
    //button is pressed to change the UI interface.
    connect(&standardGui,SIGNAL(toSeampleView(QString, QString)),
            this,SLOT(changeView(QString, QString)));

    //Connecting local slot to signal generated when a
    //button is pressed to change the UI interface.
    connect(&seampleGui,SIGNAL(toStandardView(QString, QString)),
            this,SLOT(changeView(QString, QString)));
}

void GuiControl:: showGui()
{
    if (standardViewFlag)
    {
        standardGui.show();
    }
    else
    {
        seampleGui.show();
    }
}

void GuiControl::setStandardView (bool flag)
{
    standardViewFlag = flag;
}

bool GuiControl::isStandardView()
{
    return standardViewFlag;
}

//This function is for recieving input from user and sending
//into intellisense class to interpret the text input. The
//feedback is generated to the user
void GuiControl::check(QString input)
{
    bool emptyInput = (input.size() == 0);

    if (emptyInput)
    {
        emptyResponse();
    }
    else
    {
        bool command = false;
        QVector <QString> output = inputProcessor.run(command,input.toStdString());
        send(output);
    }
}

void GuiControl::passScheduler(QString input)
{
    //Code to be implemented here to be sent into  scheduler classes
    bool emptyInput = (input.size() == 0);

    if (emptyInput)
    {
        emptyResponse();
    }
    else
    {
        bool command = true;
        QVector <QString> output = inputProcessor.run(command,input.toStdString());
        bool needStandardView = (output.size()>1);

        //Only commands to hold this should be find and search for now
        if (needStandardView)
        {
            if (!isStandardView())
            {
                changeView("",output[0]);
            }
            else
            {
                standardGui.showFeedbackInputEdit("");
                standardGui.showFeedbackLabel(output[0]);
            }
        }
        else
        {
            output.push_front("");
            send(output);
        }
    }
}

void GuiControl::changeView(QString input, QString inputChecked)
{
    setStandardView(!isStandardView());

    if(isStandardView())
    {
        seampleGui.hide();
        standardGui.show();
        standardGui.showFeedbackInputEdit(input);
        standardGui.showFeedbackLabel(inputChecked);
    }
    else
    {
        standardGui.hide();
        seampleGui.show();
        seampleGui.showFeedbackInputEdit(input);
        seampleGui.showFeedbackLabel(inputChecked);
    }
}

void GuiControl::emptyResponse()
{
    if (isStandardView())
    {
        standardGui.showFeedbackLabel(MESSAGE_AVAILABLE_COMMANDS);
    }
    else
    {
        seampleGui.showFeedbackLabel(MESSAGE_AVAILABLE_COMMANDS);
    }
}

void GuiControl::send(QVector <QString> feedback)
{
    if (isStandardView())
    {
        standardGui.showFeedbackLabel(feedback[0]);
        standardGui.showFeedbackInputEdit(feedback[1]);
    }
    else
    {
        seampleGui.showFeedbackLabel(feedback[0]);
        seampleGui.showFeedbackInputEdit(feedback[1]);
    }
}
